### ISSUE TITLE
fix normalize.css reference

### ISSUE THREAD

**Issue by mikkelmoerch** [AdditionDev/elementary-webpack-frontend#1]
Ved frisk pull og kørsel fås fejlen:

```
Refused to apply style from 'http://localhost:8081/normalize.css' 
because its MIME type ('text/html') is not a supported stylesheet MIME type,
and strict MIME checking is enabled.
```

I main.scss:

Ændre `@import "~/normalize.css"` til `@import "~normalize.css"`

Jeg kan ikke push/ lave pull request får åbenbart en 403 fejlkode, som om permission er denied på min github konto 😀

**Comment by fbosch** [comment]
Jeg har givet Frontend gruppen adgang til at commite nu.
